### ISSUE TITLE
How do I run this app?

### ISSUE THREAD

**Issue by vskid** [MrPancakes39/Desmos-Offline-Mode#5]
I apologize for not knowing how to do this, but can you please tell me how to actually run this after building? Thanks in advance

**Comment by MrPancakes39** [comment]
Note: If you just want to run and use the app you should use the [releases](https://github.com/MrPancakes39/Desmos-Offline-Mode/releases/latest) since it adds file association support,

Sure thing after building you should be able to see a `release-builds` folder appear, inside it is the app folder you go into that.
If you're on *Windows* you double click on `desmos-offline-mode.exe` and that's all.
If you're on *Linux* you need to run `desmos-offline-mode` file either by double clicking and executing it, or opening the terminal and doing `./desmos-offline-mode`.

**Comment by vskid** [comment]
Thanks for your answer, however, I'm on a mac. How do I do it in a mac? Is it similar to linux?
Again, I apologize for being on github yet not knowing how to do basic stuff like this.

**Comment by MrPancakes39** [comment]
@vskid Don't worry about it, yes exactly like Linux.

The reason I haven't released a Mac Build is that I couldn't test it on a Mac in addition to the shortcuts being Windows Style (so Ctrl instead of Cmd etc).

**Comment by MrPancakes39** [comment]
The Keyboard Shortcut Help dialog won't even show the shortcut on a Mac too so

**Comment by MrPancakes39** [comment]
@vskid here:

STEP 1:

```diff
...
-  "package-linux": "electron-packager . desmos-offline-mode --overwrite --asar=true --platform=linux --arch=x64 --icon=resources/icon.png --prune=true --out=release-builds"
+  "package-mac": "electron-packager . desmos-offline-mode --overwrite --asar=true --platform=darwin --arch=x64 --icon=resources/icon.png --prune=true --out=release-builds"
  },
...
```

You need to replace the package-linux line in `package.json` file

STEP 2:

```console
$ yarn run package-mac # or npm run package-mac
```

STEP 3:
Enter `release-builds` folder and run `desmos-offline-mode` file either by double clicking and executing it, or opening the terminal in current folder and doing `./desmos-offline-mode`.

**Comment by MrPancakes39** [comment]
Sorry I can't help you much, but rest assured that there will be a Mac release in the future. ❤️

**Comment by vskid** [comment]
It worked! Thank you so much!

**Comment by MrPancakes39** [comment]
> It worked! Thank you so much!

Glad I could help ❤️

**Comment by PIKUT0** [comment]
Hello, new here, thx :P

**Comment by PIKUT0** [comment]
It won't work, maybe I'm doing smth wrong

**Comment by MrPancakes39** [comment]
> It won't work, maybe I'm doing smth wrong

What are you doing exactly, @PIKUT0?

To download the app you should go to [releases](https://github.com/MrPancakes39/Desmos-Offline-Mode/releases/latest) page and download the `desmos-app-win32.zip` if you are on Windows or `desmos-app-linux.tar.gz` if you are on Linux.

The Windows Zip File contains an Installer that you run and it'll setup everything for you. While Linux Tar is just a tarball with the executable inside you can run.
